# Site settings
title: Criminaliteitsstatistieken / Statistiques de criminalité

email: cg.cgpr.webteam@police.belgium.eu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."



baseurl: "/crimestats2014T4/"
url: ""
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
permalink: none
